### ISSUE TITLE
Limitation of face registration and memory issues

### ISSUE THREAD

**Issue by 7thstorm** [sickidolderivative/dsm#1]
First of all, this is a great script. Thank you.

I have encountered some issues. I'll try to explain:
below is the screenshot of nvidia-smi when I start deepstack
![image](https://user-images.githubusercontent.com/47442027/108425493-89139980-7208-11eb-8f19-b16846297efd.png)

Now, I used the script to register 25 faces. Then I looked at nvidia-smi again
![image](https://user-images.githubusercontent.com/47442027/108425565-9f215a00-7208-11eb-88ea-b58b1b5dfa17.png)

as you can see memory usage shot up and stayed there. Script took around 5 seconds to execute

Next, I ran the same registration script and did another nvidia-smi
![image](https://user-images.githubusercontent.com/47442027/108425666-c4ae6380-7208-11eb-980e-346a3f15b324.png)

as you can see the memory usage remained high.

To test the theory, i stopped and restarted docker container, and then instead of this script, I used the curl command to register 31 images. It was almost instant, and the memory usage remained low

![image](https://user-images.githubusercontent.com/47442027/108425866-13f49400-7209-11eb-9443-0e30349aedf0.png)

Not sure, if there's some setting on my end or not

**Comment by radical-squared** [comment]
I noticed in your curl command that you're only submitting 2 images as all of your uploads are either image1 or image2. Try increasing the index (i.e. image3, image4) and running curl again.

**Comment by 7thstorm** [comment]
Yes, you're correct. That was an oversight on my part.
After re-running the correct curl line, my nvidia-smi now shows 3.5GB
and it stays there... is there a way to reset the memory usage, so it does not hog the system? Because if I try to rerun it yet again, it throws an error. I have to restart container again and then it will work.. In other words, I can only run that curl once before having to restart container

**Comment by 7thstorm** [comment]
Is this a memory bug in deepstack? should I open a bug over there?

**Comment by 7thstorm** [comment]
closing issue here
and opening issue on Deepstack - https://github.com/johnolafenwa/DeepStack/issues/93
